# Generated by Django 5.1.2 on 2026-05-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapeuta',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='terapeutas', to='terapeutas.especialidade'),
        ),
    ]
