# Generated by Django 5.1.2 on 2026-05-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0002_alter_terapeuta_especialidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terapeuta',
            name='especialidades',
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='especialidades',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
