# Generated by Django 5.2.13 on 2026-05-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0003_remove_terapeuta_especialidades_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Especialidade',
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='especialidades',
            field=models.CharField(blank=True, choices=[('', 'Selecione uma especialidade'), ('Fonoaudiologia', 'Fonoaudiologia'), ('Terapia Ocupacional', 'Terapia Ocupacional'), ('Fisioterapia', 'Fisioterapia'), ('Psicologia', 'Psicologia'), ('Psicopedagogia', 'Psicopedagogia'), ('Neuropsicologia', 'Neuropsicologia'), ('Musicoterapia', 'Musicoterapia'), ('Hidroterapia', 'Hidroterapia'), ('ABA (Análise do Comportamento Aplicada)', 'ABA (Análise do Comportamento Aplicada)'), ('Educação Especial', 'Educação Especial'), ('Neuropediatria', 'Neuropediatria'), ('Nutrição', 'Nutrição')], max_length=255, null=True),
        ),
    ]
