# Generated by Django 5.1.2 on 2026-05-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cid',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
