# Generated by Django 5.1.2 on 2026-05-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='terapeutas_responsaveis',
        ),
    ]
