# Generated by Django 5.1.2 on 2026-05-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_remove_paciente_terapeutas_responsaveis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='contato',
            field=models.CharField(max_length=11),
        ),
    ]
