# Generated by Django 5.1.2 on 2026-05-06 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_paciente_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='observacoes',
        ),
    ]
