# Generated by Django 5.2.13 on 2026-05-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0005_remove_paciente_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_aula', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Presença em Aula',
                'verbose_name_plural': 'Presenças em Aula',
                'ordering': ['data', 'paciente__nome'],
                'unique_together': {('paciente', 'data')},
            },
        ),
    ]
